webtalk_init -webtalk_dir C:/Users/rajit/OneDrive/Documents/GitHub/RISCV_IoT/src/Vivado_project/project_1/project_1.sim/sim_1/behav/xsim.dir/branch_check_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Dec 27 10:05:55 2016" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2016.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1577090" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "176453893_200471044_210637353_003" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "e3ae2bcb-0b4d-4869-97af-953ecd4afbbd" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "37963d2806f74f2987e15a5fae16a2e6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2400 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "12.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "70 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "8928_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3766328089 -regid "176453893_200471044_210637353_003" -xml C:/Users/rajit/OneDrive/Documents/GitHub/RISCV_IoT/src/Vivado_project/project_1/project_1.sim/sim_1/behav/xsim.dir/branch_check_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/rajit/OneDrive/Documents/GitHub/RISCV_IoT/src/Vivado_project/project_1/project_1.sim/sim_1/behav/xsim.dir/branch_check_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/rajit/OneDrive/Documents/GitHub/RISCV_IoT/src/Vivado_project/project_1/project_1.sim/sim_1/behav/xsim.dir/branch_check_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
